Fix spec flicker
Specifying the id occassionally causes:
```
Failure/Error: let(:creator_external_user) { create(:external_user, provider: provider, id: 201) }

ActiveRecord::RecordNotUnique:
  PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "external_users_pkey"
  DETAIL:  Key (id)=(201) already exists.
./spec/mailers/notify_mailer_spec.rb:13:in `block (3 levels) in <top (required)>'
./spec/mailers/notify_mailer_spec.rb:18:in `block (3 levels) in <top (required)>'
./spec/vcr_helper.rb:83:in `block (3 levels) in <top (required)>'
./spec/vcr_helper.rb:82:in `block (2 levels) in <top (required)>'
--- Caused by: ---
PG::UniqueViolation:
  ERROR:  duplicate key value violates unique constraint "external_users_pkey"
  DETAIL:  Key (id)=(201) already exists.
  ./spec/mailers/notify_mailer_spec.rb:13:in `block (3 levels) in <top (required)>'

```