Quote column names (and everything else) when writing to dump file
Quotes needed to ensure restore from the dump does
not encounter errors resulting from reservered
keywords. The column names claim_state_transitions#from
and claim_state_transitions#to are reserved words which
result in an error if they unquoted.

```
INSERT INTO claims_state_transitions (...,from, to) VALUES (...)
```

causes an error such as below when run:
```
ERROR:  syntax error at or near "from"
LINE 1: ...tate_transitions (id, claim_id, namespace, event, from, to, ...
                                                             ^
```

It is unclear from the history why this was removed but it could
have been:
a. to recduce overall file size
b. some other table or column naming issue??! (need to try a full
db dump and restore to test)