Add environment to rake task (#4056)
Add environment to rake task

This was working previously but is currently broken.
Its unclear if this is a rails 6.1 issue or related
to rake version currenly bundled but the task was raising
the following error. The task should have an envn anyway.

```
bundle exec rake db:reload
=>
NoMethodError: undefined method `host' for Rails:Module
lib/tasks/rake_helpers/rake_utils.rb:30:in `production_protected'
lib/tasks/db.rake:63:in `block (2 levels) in <top (required)>'
```