Handle error raised by storage:status rake task via cronjob
Not clear why this happended after all record checksums
were added.

```
NoMethodError: undefined method `document_file_name' for nil:NilClass
/usr/src/app/lib/tasks/rake_helpers/storage.rb:270:in `block in validate'
/usr/local/bundle/gems/activerecord-6.0.3.5/lib/active_record/relation/delegation.rb:87:in `each'
/usr/local/bundle/gems/activerecord-6.0.3.5/lib/active_record/relation/delegation.rb:87:in `each'
/usr/src/app/lib/tasks/rake_helpers/storage.rb:268:in `each_with_object'
/usr/src/app/lib/tasks/rake_helpers/storage.rb:268:in `validate'
/usr/src/app/lib/tasks/rake_helpers/storage.rb:210:in `status'
/usr/src/app/lib/tasks/storage.rake:102:in `block (2 levels) in <top (required)>'
/usr/src/app/lib/tasks/storage.rake:90:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/railties-6.0.3.5/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/usr/local/bundle/gems/railties-6.0.3.5/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/usr/local/bundle/gems/railties-6.0.3.5/lib/rails/command.rb:48:in `invoke'
/usr/local/bundle/gems/railties-6.0.3.5/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => storage:status
```