Fix failing specs due to no longer supported sanitised method
```
      NoMethodError:
        undefined method `sanitize' for ActiveRecord::Base:Class
```

Use `quote` instead.